### ISSUE TITLE
University login not working for me

### ISSUE THREAD

**Issue by lovetoflyguy** [davejm/plugin.video.lynda#4]
I'm getting a script error when launching the plugin with university login. I tried configuring with just my university domain (wgu.edu) filled in, and upon failure filled in username & password fields on subsequent attempts. Log file included.

I'm a n00b with python, but might be able to help debug.

Note: I've edited out the irrelevant sections of my log file.
[LyndaScriptError.log.txt](https://github.com/davejm/plugin.video.lynda/files/367652/LyndaScriptError.log.txt)

**Comment by davejm** [comment]
Hi there @lovetoflyguy . I took a look at the login page for your org and it's because the signin form uses javascript. This highlights a wider issue which is that my plugin tries its best to generalise to different org's login pages but sometimes needs tweaking. In this case the form for the login has an action of 'blank' (the actual action is handled by javascript) which is picked up by my plugin and so that is the page that is submitted, hence the error in the log about invalid url 'blank'. I'll see if there's a way to generalise a fix for javascript enabled forms. If not, might have to program a custom case for your domain.

**Comment by davejm** [comment]
Unfortunately there seems to be no pure python headless web client that supports javascript so the only real viable way to do this is to create a special rule for your organization. I'll look into this when I can.

**Comment by lovetoflyguy** [comment]
Thanks David.  Please let me know if I can help in any way.
